#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob
btrfs_path='/var/bocker' && cgroup_path='/sys/fs/cgroup/bocker';
[[ $# -gt 0 ]] && while [ "${1:0:2}" == '--' ]; do OPTION=${1:2}; [[ $OPTION =~ = ]] && declare "BOCKER_${OPTION/=*/}=${OPTION/*=/}" || declare "BOCKER_${OPTION}=x"; shift; done

function bocker_check() {
	btrfs subvolume list "$btrfs_path" | grep -qw "$1" && echo 0 || echo 1
}

function bocker_init() { #HELP Create an image from a directory:\nBOCKER init <directory>
	uuid="img_$(shuf -i 42002-42254 -n 1)"
	if [[ -d "$1" ]]; then
		[[ "$(bocker_check "$uuid")" == 0 ]] && bocker_run "$@"
		btrfs subvolume create "$btrfs_path/$uuid" > /dev/null
		cp -rf --reflink=auto "$1"/* "$btrfs_path/$uuid" > /dev/null
		[[ ! -f "$btrfs_path/$uuid"/img.source ]] && echo "$1" > "$btrfs_path/$uuid"/img.source
		echo "Created: $uuid"
	else
		echo "No directory named '$1' exists"
	fi
}

function bocker_pull() { #HELP Pull an image from Docker Hub:\nBOCKER pull <name> <tag>
	image="$1" && tag="$2"
	[[ "$image" != */* ]] && image="library/$image"
	registry='https://registry-1.docker.io/v2'
	accept='Accept: application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json'
	token="$(curl -sL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${image}:pull" | jq -r '.token')"
	manifest="$(curl -sL -H "Authorization: Bearer $token" -H "$accept" "$registry/$image/manifests/$tag")"
	if echo "$manifest" | jq -e 'has("manifests")' > /dev/null 2>&1; then
		digest="$(echo "$manifest" | jq -r '[.manifests[] | select(.platform.os == "linux" and .platform.architecture == "amd64")][0].digest' 2> /dev/null || true)"
		[[ -z "$digest" || "$digest" == 'null' ]] && echo "No linux/amd64 image for '$1:$2'" && exit 1
		manifest="$(curl -sL -H "Authorization: Bearer $token" -H "$accept" "$registry/$image/manifests/$digest")"
	fi
	layers="$(echo "$manifest" | jq -r '.layers[]?.digest' 2> /dev/null || true)"
	[[ -z "$layers" ]] && echo "No image named '$1:$2' exists" && exit 1
	tmp_uuid="$(uuidgen)" && mkdir /tmp/"$tmp_uuid"
	for layer in $layers; do
		curl -#L -H "Authorization: Bearer $token" "$registry/$image/blobs/$layer" -o /tmp/"$tmp_uuid"/layer.tar
		tar xf /tmp/"$tmp_uuid"/layer.tar -C /tmp/"$tmp_uuid" && rm /tmp/"$tmp_uuid"/layer.tar
	done
	echo "$1:$2" > /tmp/"$tmp_uuid"/img.source
	bocker_init /tmp/"$tmp_uuid" && rm -rf /tmp/"$tmp_uuid"
}

function bocker_rm() { #HELP Delete an image or container:\nBOCKER rm <image_id or container_id>
	[[ "$(bocker_check "$1")" == 1 ]] && echo "No container named '$1' exists" && exit 1
	btrfs subvolume delete "$btrfs_path/$1" > /dev/null
	[[ -d "$cgroup_path/$1" ]] && rmdir "$cgroup_path/$1" 2> /dev/null || true
	echo "Removed: $1"
}

function bocker_images() { #HELP List images:\nBOCKER images
	echo -e "IMAGE_ID\t\tSOURCE"
	for img in "$btrfs_path"/img_*; do
		img=$(basename "$img")
		echo -e "$img\t\t$(cat "$btrfs_path/$img/img.source")"
	done
}

function bocker_ps() { #HELP List containers:\nBOCKER ps
	echo -e "CONTAINER_ID\t\tCOMMAND"
	for ps in "$btrfs_path"/ps_*; do
		ps=$(basename "$ps")
		echo -e "$ps\t\t$(cat "$btrfs_path/$ps/$ps.cmd")"
	done
}

function bocker_run() { #HELP Create a container:\nBOCKER run <image_id> <command>\nLimits: BOCKER_CPU_WEIGHT (1-10000, default 100), BOCKER_MEM_LIMIT (MB, default 512)
	uuid="ps_$(shuf -i 42002-42254 -n 1)"
	[[ "$(bocker_check "$1")" == 1 ]] && echo "No image named '$1' exists" && exit 1
	[[ "$(bocker_check "$uuid")" == 0 ]] && echo "UUID conflict, retrying..." && bocker_run "$@" && return
	cmd="${@:2}" && ip="$(echo "${uuid: -3}" | sed 's/0//g')" && mac="${uuid: -3:1}:${uuid: -2}"
	ip link add dev veth0_"$uuid" type veth peer name veth1_"$uuid"
	ip link set dev veth0_"$uuid" up
	ip link set veth0_"$uuid" master bridge0
	ip netns add netns_"$uuid"
	ip link set veth1_"$uuid" netns netns_"$uuid"
	ip netns exec netns_"$uuid" ip link set dev lo up
	ip netns exec netns_"$uuid" ip link set veth1_"$uuid" address 02:42:ac:11:00"$mac"
	ip netns exec netns_"$uuid" ip addr add 10.0.0."$ip"/24 dev veth1_"$uuid"
	ip netns exec netns_"$uuid" ip link set dev veth1_"$uuid" up
	ip netns exec netns_"$uuid" ip route add default via 10.0.0.1
	btrfs subvolume snapshot "$btrfs_path/$1" "$btrfs_path/$uuid" > /dev/null
	echo 'nameserver 8.8.8.8' > "$btrfs_path/$uuid"/etc/resolv.conf
	echo "$cmd" > "$btrfs_path/$uuid/$uuid.cmd"
	mkdir -p "$cgroup_path/$uuid"
	: "${BOCKER_CPU_WEIGHT:=100}"; : "${BOCKER_MEM_LIMIT:=512}"
	if [[ -w "$cgroup_path/$uuid/cpu.weight" ]]; then echo "$BOCKER_CPU_WEIGHT" > "$cgroup_path/$uuid/cpu.weight" || true; fi
	if [[ -w "$cgroup_path/$uuid/memory.max" ]]; then echo "$((BOCKER_MEM_LIMIT * 1000000))" > "$cgroup_path/$uuid/memory.max" || true; fi
	(
		if [[ -w "$cgroup_path/$uuid/cgroup.procs" ]]; then echo "$BASHPID" > "$cgroup_path/$uuid/cgroup.procs" || true; fi
		exec ip netns exec netns_"$uuid" \
			unshare -fmuip --mount-proc \
			chroot "$btrfs_path/$uuid" \
			/bin/sh -c "/bin/mount -t proc proc /proc && $cmd"
	) 2>&1 | tee "$btrfs_path/$uuid/$uuid.log" || true
	ip link del dev veth0_"$uuid"
	ip netns del netns_"$uuid"
}

function bocker_exec() { #HELP Execute a command in a running container:\nBOCKER exec <container_id> <command>
	[[ "$(bocker_check "$1")" == 1 ]] && echo "No container named '$1' exists" && exit 1
	unshare_pid="$(ps -eo pid,args | awk -v id="$1" '$0 ~ ("unshare -fmuip.*" id) { print $1; exit }')"
	[[ -z "$unshare_pid" ]] && echo "Container '$1' exists but is not running" && exit 1
	cid="$(ps -eo ppid,pid | awk -v p="$unshare_pid" '$1 == p { print $2; exit }')"
	[[ -z "$cid" ]] && echo "Container '$1' exists but is not running" && exit 1
	nsenter -t "$cid" -m -u -i -n -p chroot "$btrfs_path/$1" "${@:2}"
}

function bocker_logs() { #HELP View logs from a container:\nBOCKER logs <container_id>
	[[ "$(bocker_check "$1")" == 1 ]] && echo "No container named '$1' exists" && exit 1
	cat "$btrfs_path/$1/$1.log"
}

function bocker_commit() { #HELP Commit a container to an image:\nBOCKER commit <container_id> <image_id>
	[[ "$(bocker_check "$1")" == 1 ]] && echo "No container named '$1' exists" && exit 1
	[[ "$(bocker_check "$2")" == 1 ]] && echo "No image named '$2' exists" && exit 1
	bocker_rm "$2" && btrfs subvolume snapshot "$btrfs_path/$1" "$btrfs_path/$2" > /dev/null
	echo "Created: $2"
}

function bocker_help() { #HELP Display this message:\nBOCKER help
	sed -n "s/^.*#HELP\\s//p;" < "$1" | sed "s/\\\\n/\n\t/g;s/$/\n/;s!BOCKER!${1/!/\\!}!g"
}

[[ -z "${1-}" ]] && bocker_help "$0"
case $1 in
	pull|init|rm|images|ps|run|exec|logs|commit) bocker_"$1" "${@:2}" ;;
	*) bocker_help "$0" ;;
esac
