#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

img="$(./bocker init ~/base-image | awk '{print $2}')"
./bocker images | grep -qw "$img"
[[ "$?" == 0 ]]

./bocker run "$img" which curl
ps="$(./bocker ps | grep 'which curl' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
./bocker rm "$ps"
[[ "$logs" != *"/usr/bin/curl"* ]]

./bocker run "$img" apk add --no-cache curl
ps="$(./bocker ps | grep 'apk add --no-cache curl' | awk '{print $1}')"
./bocker commit "$ps" "$img"

./bocker run "$img" which curl
ps="$(./bocker ps | grep 'which curl' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
[[ "$logs" == '/usr/bin/curl' ]]
