#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

img="$(./bocker init ~/base-image | awk '{print $2}')"
./bocker images | grep -qw "$img"
[[ "$?" == 0 ]]

# ▼ ▼ ▼ Race condition waiting to happen ▼ ▼ ▼
./bocker run "$img" "sleep 5 && echo done" &
sleep 2
ps="$(./bocker ps | grep 'sleep 5' | awk '{print $1}')"
exec="$(./bocker exec "$ps" echo hi-from-exec)"
[[ "$exec" == 'hi-from-exec' ]]
sleep 4
# ▲ ▲ ▲ Race condition waiting to happen ▲ ▲ ▲

./bocker run "$img" "echo hi"
ps="$(./bocker ps | grep 'echo hi' | awk '{print $1}')"
exec="$(./bocker exec "$ps" echo x)" || true
[[ "$exec" == "Container '$ps' exists but is not running" ]]

exec="$(./bocker exec foo ps aux)" || true
[[ "$exec" == "No container named 'foo' exists" ]]
