#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

alpine_img="$(./bocker pull alpine 3.19 2> /dev/null | awk '{print $2}')"
./bocker run "$alpine_img" cat /etc/alpine-release
ps="$(./bocker ps | grep 'cat /etc/alpine-release' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
./bocker rm "$ps"
[[ "$logs" == "3.19"* ]]

debian_img="$(./bocker pull debian bookworm-slim 2> /dev/null | awk '{print $2}')"
./bocker run "$debian_img" cat /etc/debian_version
ps="$(./bocker ps | grep 'cat /etc/debian_version' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
./bocker rm "$ps"
[[ "$logs" == "12."* ]]

missing="$(./bocker pull nosuchimage 0.0.0 2>&1 || true)"
[[ "$missing" == *"No image named"* ]]
